# Base Image
From ubuntu

# Author Name
MAINTAINER Anas

# Update Command
RUN apt update

# Executable Command
CMD ["echo","This is my ubuntu image"]

# ! Terminal Command
# docker build -t ubuntuimage .